version: "3.7"

services:
  react-app:
    build: ./pokedex
    stdin_open: true
    ports:
      - "3000:3000"


  pokemonapi:
    build:
      context: ./flaskApplication
    volumes: 
      - ./flaskApplication:/app
    ports:
      - 5000:5000